### ISSUE TITLE
arguments JsonLocalizationSource

### ISSUE THREAD

**Issue by danijerez** [saeidjoker/libc.translation#10]
currently the 'JsonLocalizationSource' class needs to be case sensitive. sample:

ILocalizationSource source = new JsonLocalizationSource(stream, PropertyCaseSensitivity.CaseInsensitive);

in case you want to modify it in your usage examples.

**Comment by saeidjoker** [comment]
@danijerez Sorry to answer so late, been busy. Thank you for the suggestions. Readme file is updated :-)
