### ISSUE TITLE
French accent not encoded

### ISSUE THREAD

**Issue by antoine1003** [saeidjoker/libc.translation#7]
Hi,

I use your library with English and french string. All English strings are properly retrieved but some french word containing accent are skipped. For example `Activité projet` will be display in PDF like `Activit projet`.

Do you have an idea about that?
Thanks

**Comment by saeidjoker** [comment]
Hi Antoine,

I don't think that it is related to this library cause this library doesn't enforce any kind of text encoding on C# string datatype.

Anyway I will take a look into French, and I'll write tests for it ASAP.

**Comment by antoine1003** [comment]
Okay thanks a lot, I'll look at my code. Maybe I'm doing something wrong :)

**Comment by saeidjoker** [comment]
You're welcome :-) Anyway if you need any need help with your code I'm available.

**Comment by antoine1003** [comment]
Cool it's really kind of you. I'll ask you if I need some help 😄
